// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package_0413

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0413Client is the client API for Zhaoh0413 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0413Client interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0413Client struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0413Client(cc grpc.ClientConnInterface) Zhaoh0413Client {
	return &zhaoh0413Client{cc}
}

func (c *zhaoh0413Client) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/sample_module_0413.sample_package_0413.Zhaoh0413/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zhaoh0413Client) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0413.sample_package_0413.Zhaoh0413/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0413Server is the server API for Zhaoh0413 service.
// All implementations must embed UnimplementedZhaoh0413Server
// for forward compatibility
type Zhaoh0413Server interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0413Server()
}

// UnimplementedZhaoh0413Server must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0413Server struct {
}

func (UnimplementedZhaoh0413Server) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedZhaoh0413Server) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedZhaoh0413Server) mustEmbedUnimplementedZhaoh0413Server() {}

// UnsafeZhaoh0413Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0413Server will
// result in compilation errors.
type UnsafeZhaoh0413Server interface {
	mustEmbedUnimplementedZhaoh0413Server()
}

func RegisterZhaoh0413Server(s grpc.ServiceRegistrar, srv Zhaoh0413Server) {
	s.RegisterService(&Zhaoh0413_ServiceDesc, srv)
}

func _Zhaoh0413_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0413Server).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0413.sample_package_0413.Zhaoh0413/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0413Server).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zhaoh0413_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0413Server).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0413.sample_package_0413.Zhaoh0413/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0413Server).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0413_ServiceDesc is the grpc.ServiceDesc for Zhaoh0413 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0413_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0413.sample_package_0413.Zhaoh0413",
	HandlerType: (*Zhaoh0413Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _Zhaoh0413_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _Zhaoh0413_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Zhaoh0413.proto",
}
